name: Daily Run

on:
  schedule:
    - cron: '23 15 * * *'  # Runs every day at 15:30 UTC, which is 16:30 BST

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python fetch_data.py
