name: Daily Run

on:
  schedule:
    - cron: '00 16 * * *'  # This is your scheduled time (15:30 UTC for 16:30 BST)
  workflow_dispatch:  # This enables manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python fetch_data.py  # Replace with your actual script name
