name: Run Reddit and Snowflake Script Weekly

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:

  # Schedule to run every Sunday at midnight (UTC)
  schedule:
    - cron: '0 0 * * 0'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository using the updated version
    - name: Check out the repository
      uses: actions/checkout@v3  # Updated to v3

    # Step 2: Set up Python using the updated version
    - name: Set up Python 3.x
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the Python script
    - name: Run Python script
      env:
        # Pass Reddit API credentials from GitHub Secrets
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USER_AGENT: ${{ secrets.USER_AGENT }}

        # Pass Snowflake connection parameters from GitHub Secrets
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      run: python fetch_data.py
